# Generated by Django 5.2.10 on 2026-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
