# Generated by Django 5.2.10 on 2026-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
