# Generated by Codex on 2026-04-24

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def seed_coffee_products(apps, schema_editor):
    CoffeeProduct = apps.get_model("api", "CoffeeProduct")

    products = [
        {
            "name": "Toba Sunrise",
            "slug": "toba-sunrise",
            "tagline": "Medium roast dengan nuansa caramel dan rempah hangat.",
            "description": "Cocok untuk penikmat kopi pagi dengan body lembut dan aroma yang terasa tenang namun berkarakter.",
            "origin": "Danau Toba, Sumatera Utara",
            "roast_level": "medium",
            "price": Decimal("68000.00"),
            "intensity": 3,
            "is_featured": True,
            "is_available": True,
        },
        {
            "name": "Batak Bold",
            "slug": "batak-bold",
            "tagline": "Dark roast untuk pecinta rasa tegas dan aftertaste panjang.",
            "description": "Varian dengan karakter lebih kuat, smoky, dan cocok untuk espresso maupun tubruk.",
            "origin": "Humbang Highlands",
            "roast_level": "dark",
            "price": Decimal("74000.00"),
            "intensity": 5,
            "is_featured": True,
            "is_available": True,
        },
        {
            "name": "Lake Mist",
            "slug": "lake-mist",
            "tagline": "Light roast yang floral dan cerah untuk manual brew.",
            "description": "Pilihan yang lebih ringan dengan aroma fresh dan profil rasa yang elegan.",
            "origin": "Samosir Ridge",
            "roast_level": "light",
            "price": Decimal("71000.00"),
            "intensity": 2,
            "is_featured": False,
            "is_available": True,
        },
    ]

    for product in products:
        CoffeeProduct.objects.update_or_create(slug=product["slug"], defaults=product)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_belanja"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Belanja",
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
        migrations.CreateModel(
            name="CoffeeProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("tagline", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("origin", models.CharField(default="Danau Toba, Sumatera Utara", max_length=120)),
                ("roast_level", models.CharField(choices=[("light", "Light Roast"), ("medium", "Medium Roast"), ("dark", "Dark Roast")], default="medium", max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("intensity", models.PositiveSmallIntegerField(default=3)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="CoffeeOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=30)),
                ("address", models.TextField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("grind_size", models.CharField(choices=[("beans", "Biji utuh"), ("fine", "Fine grind"), ("medium", "Medium grind"), ("coarse", "Coarse grind")], default="beans", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("brewing", "Brewing"), ("delivered", "Delivered"), ("canceled", "Canceled")], default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("coffee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="api.coffeeproduct")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_coffee_products, migrations.RunPython.noop),
    ]
